[build]
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/assets/*"
  to = "/dist/public/assets/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[functions]]
  name = "server"
  bundler = "esbuild"
  esbuild_target = "es2020" # Or a more recent ECMAScript version
  external_node_modules = ["serverless-http"] # Explicitly list external modules