[build]
  publish = "dist/public"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/server/*"
  to = "/.netlify/functions/server/:splat"
  status = 200