[build]
  publish = "dist/public"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[functions]
  included_files = ["server/**", "node_modules/@neondatabase/**"]
  external_node_modules = ["rollup"]